# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-04-10 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('status', models.CharField(choices=[('OP', 'OPEN'), ('CL', 'CLOSED')], max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
