# Generated by Django 3.2 on 2021-04-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210412_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='employee',
            name='password2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
