# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-04-10 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(),
        ),
    ]
