# Generated by Django 3.2 on 2021-04-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20210413_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('PENDING', 'PENDING'), ('CLOSED', 'CLOSED')], max_length=50),
        ),
    ]
